openapi: 3.0.3
info:
  title: Agent Commerce API
  version: "0.4.0"
  description: |
    Extract structured product information from e-commerce pages (Amazon, Flipkart, Myntra, etc.)
    and audit store readiness for AI agents.
servers:
  - url: https://agent-commerce-api.onrender.com
    description: Render server (your backend)

paths:
  /audit:
    post:
      summary: Audit an e-commerce product page
      description: >
        Given a product page URL from Flipkart, Amazon, or Myntra,
        this endpoint extracts structured data (name, price, availability, etc.),
        evaluates agent-readiness, and returns recommendations.
      operationId: auditStore
      security:
        - rapidapiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  format: uri
                  example: "https://www.flipkart.com/aqua-fresh-smoke-audi-18-ltr-water-purifier/p/itmc3da457d7de29"
      responses:
        "200":
          description: Successful audit response
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    format: uri
                  product_info:
                    type: object
                    properties:
                      name: { type: string }
                      price: { type: number }
                      price_raw: { type: string }
                      currency: { type: string }
                      availability: { type: string }
                      images:
                        type: array
                        items: { type: string, format: uri }
                      description: { type: string }
                      brand: { type: string }
                      sku: { type: string }
                      rating: { type: number }
                      reviews_count: { type: integer }
                      raw_html_excerpt: { type: string }
                  score:
                    type: number
                    description: Audit score (0–100)
                  recommendations:
                    type: array
                    items: { type: string }
                  fetched_via:
                    type: string
                    description: "Fetcher used (playwright | proxy | httpx)"
                  fetched_at:
                    type: string
                    format: date-time
        "401":
          description: Missing or invalid API key
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail: { type: string, example: "Missing API key" }
        "422":
          description: Could not extract product info
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail: { type: string, example: "Could not extract product info from target page" }
        "502":
          description: Failed to fetch target page
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail: { type: string, example: "Failed to fetch target page" }

components:
  securitySchemes:
    rapidapiKey:
      type: apiKey
      in: header
      name: X-RapidAPI-Key
security:
  - rapidapiKey: []
